-- Stop NS2+ from loading
ModLoader.SetupFileHook("lua/NS2Plus/CHUD_Client.lua", "", "halt")
ModLoader.SetupFileHook("lua/NS2Plus/CHUD_Server.lua", "", "halt")
ModLoader.SetupFileHook("lua/NS2Plus/CHUD_Shared.lua", "", "halt")
ModLoader.SetupFileHook("lua/NS2Plus/CHUD_FileHooks.lua", "", "halt") 
-- Hook GRfiles
ModLoader.SetupFileHook( "lua/NS2Gamerules.lua", "lua/GorgeRun/NS2Gamerules.lua", "post" )
ModLoader.SetupFileHook( "lua/AlienTeam.lua", "lua/GorgeRun/AlienTeam.lua", "post" )
ModLoader.SetupFileHook( "lua/TeamInfo.lua", "lua/GorgeRun/TeamInfo.lua", "post" )
ModLoader.SetupFileHook( "lua/Balance.lua", "lua/GorgeRun/Balance.lua", "post" )
ModLoader.SetupFileHook( "lua/TeamJoin.lua", "lua/GorgeRun/TeamJoin.lua", "post" )
ModLoader.SetupFileHook( "lua/CommandStructure_Server.lua", "lua/GorgeRun/CommandStructure_Server.lua", "post" )
ModLoader.SetupFileHook( "lua/GUIReadyRoomOrders.lua", "lua/GorgeRun/GUIReadyRoomOrders.lua", "post" )
ModLoader.SetupFileHook( "lua/NS2ConsoleCommands_Server.lua", "lua/GorgeRun/NS2ConsoleCommands_Server.lua", "post" )
ModLoader.SetupFileHook( "lua/GUIMinimap.lua", "lua/GorgeRun/GUIMinimap.lua", "post" )
ModLoader.SetupFileHook( "lua/Alien_Server.lua", "lua/GorgeRun/Alien_Server.lua", "post" )
ModLoader.SetupFileHook( "lua/Hud/GUIPlayerResource.lua", "lua/GorgeRun/GUIPlayerResource.lua", "post" )
ModLoader.SetupFileHook( "lua/ClientUI.lua", "lua/GorgeRun/ClientUI.lua", "post" )
ModLoader.SetupFileHook( "lua/Sentry.lua", "lua/GorgeRun/Sentry.lua", "post" )
ModLoader.SetupFileHook( "lua/BalanceMisc.lua", "lua/GorgeRun/BalanceMisc.lua", "post" )
ModLoader.SetupFileHook( "lua/Clog.lua", "lua/GorgeRun/Clog.lua", "post" )
ModLoader.SetupFileHook( "lua/Gamerules.lua", "lua/GorgeRun/Gamerules.lua", "post" )
ModLoader.SetupFileHook( "lua/NS2Utility.lua", "lua/GorgeRun/NS2Utility.lua", "post" )

ModLoader.SetupFileHook("lua/ConfigFileUtility.lua", "lua/GorgeRun/ShineHook.lua", "post" )